#!/bin/bash

# Prints the backlight percentage
# Requires the light package

# PREFIX='ﯧ'
PREFIX='盛'

get_backlight()
{
    # echo "$PREFIX $(brightnessctl g)%"
    echo "$PREFIX$(( $(brightnessctl g)/192 ))%"
}

get_backlight
